services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks: 
      - network1


networks:
  network1:
    name: db-back
    external: true

