---
- name: Setup and configure the EC2 instance
  hosts: web
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - git
          - nginx
        state: present

    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple index.html
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Hello from Ansible managed instance!</h1>"
